/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MICRO_MCP_MCP_PB_H_INCLUDED
#define PB_MICRO_MCP_MCP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _micro_mcp_InitializeRequest {
    char protocol_version[16];
    char client_name[32];
    char client_version[16];
} micro_mcp_InitializeRequest;

typedef struct _micro_mcp_InitializeResponse {
    char protocol_version[16];
    char server_name[32];
    char server_version[16];
} micro_mcp_InitializeResponse;

typedef struct _micro_mcp_Tool {
    char name[32];
    char description[64];
    char input_schema_json[128];
} micro_mcp_Tool;

typedef struct _micro_mcp_ListToolsResponse {
    pb_size_t tools_count;
    micro_mcp_Tool tools[10];
} micro_mcp_ListToolsResponse;

typedef struct _micro_mcp_CallToolRequest {
    char name[32];
    char arguments_json[256];
} micro_mcp_CallToolRequest;

typedef struct _micro_mcp_CallToolResponse {
    char content_text[256];
    bool is_error;
} micro_mcp_CallToolResponse;

typedef struct _micro_mcp_Resource {
    char uri[64];
    char name[32];
    char description[64];
    char mime_type[32];
} micro_mcp_Resource;

typedef struct _micro_mcp_ListResourcesResponse {
    pb_size_t resources_count;
    micro_mcp_Resource resources[10];
} micro_mcp_ListResourcesResponse;

typedef struct _micro_mcp_ReadResourceRequest {
    char uri[64];
} micro_mcp_ReadResourceRequest;

typedef struct _micro_mcp_ReadResourceResponse {
    char contents_text[512];
} micro_mcp_ReadResourceResponse;

typedef struct _micro_mcp_McpMessage {
    int32_t id; /* JSON-RPC message ID */
    pb_size_t which_message_type;
    union {
        micro_mcp_InitializeRequest init_req;
        micro_mcp_InitializeResponse init_res;
        bool list_tools_req; /* True to request */
        micro_mcp_ListToolsResponse list_tools_res;
        micro_mcp_CallToolRequest call_tool_req;
        micro_mcp_CallToolResponse call_tool_res;
        bool list_resources_req;
        micro_mcp_ListResourcesResponse list_resources_res;
        micro_mcp_ReadResourceRequest read_resource_req;
        micro_mcp_ReadResourceResponse read_resource_res;
        char error_message[128];
    } message_type;
} micro_mcp_McpMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define micro_mcp_InitializeRequest_init_default {"", "", ""}
#define micro_mcp_InitializeResponse_init_default {"", "", ""}
#define micro_mcp_Tool_init_default              {"", "", ""}
#define micro_mcp_ListToolsResponse_init_default {0, {micro_mcp_Tool_init_default, micro_mcp_Tool_init_default, micro_mcp_Tool_init_default, micro_mcp_Tool_init_default, micro_mcp_Tool_init_default, micro_mcp_Tool_init_default, micro_mcp_Tool_init_default, micro_mcp_Tool_init_default, micro_mcp_Tool_init_default, micro_mcp_Tool_init_default}}
#define micro_mcp_CallToolRequest_init_default   {"", ""}
#define micro_mcp_CallToolResponse_init_default  {"", 0}
#define micro_mcp_Resource_init_default          {"", "", "", ""}
#define micro_mcp_ListResourcesResponse_init_default {0, {micro_mcp_Resource_init_default, micro_mcp_Resource_init_default, micro_mcp_Resource_init_default, micro_mcp_Resource_init_default, micro_mcp_Resource_init_default, micro_mcp_Resource_init_default, micro_mcp_Resource_init_default, micro_mcp_Resource_init_default, micro_mcp_Resource_init_default, micro_mcp_Resource_init_default}}
#define micro_mcp_ReadResourceRequest_init_default {""}
#define micro_mcp_ReadResourceResponse_init_default {""}
#define micro_mcp_McpMessage_init_default        {0, 0, {micro_mcp_InitializeRequest_init_default}}
#define micro_mcp_InitializeRequest_init_zero    {"", "", ""}
#define micro_mcp_InitializeResponse_init_zero   {"", "", ""}
#define micro_mcp_Tool_init_zero                 {"", "", ""}
#define micro_mcp_ListToolsResponse_init_zero    {0, {micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero, micro_mcp_Tool_init_zero}}
#define micro_mcp_CallToolRequest_init_zero      {"", ""}
#define micro_mcp_CallToolResponse_init_zero     {"", 0}
#define micro_mcp_Resource_init_zero             {"", "", "", ""}
#define micro_mcp_ListResourcesResponse_init_zero {0, {micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero, micro_mcp_Resource_init_zero}}
#define micro_mcp_ReadResourceRequest_init_zero  {""}
#define micro_mcp_ReadResourceResponse_init_zero {""}
#define micro_mcp_McpMessage_init_zero           {0, 0, {micro_mcp_InitializeRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define micro_mcp_InitializeRequest_protocol_version_tag 1
#define micro_mcp_InitializeRequest_client_name_tag 2
#define micro_mcp_InitializeRequest_client_version_tag 3
#define micro_mcp_InitializeResponse_protocol_version_tag 1
#define micro_mcp_InitializeResponse_server_name_tag 2
#define micro_mcp_InitializeResponse_server_version_tag 3
#define micro_mcp_Tool_name_tag                  1
#define micro_mcp_Tool_description_tag           2
#define micro_mcp_Tool_input_schema_json_tag     3
#define micro_mcp_ListToolsResponse_tools_tag    1
#define micro_mcp_CallToolRequest_name_tag       1
#define micro_mcp_CallToolRequest_arguments_json_tag 2
#define micro_mcp_CallToolResponse_content_text_tag 1
#define micro_mcp_CallToolResponse_is_error_tag  2
#define micro_mcp_Resource_uri_tag               1
#define micro_mcp_Resource_name_tag              2
#define micro_mcp_Resource_description_tag       3
#define micro_mcp_Resource_mime_type_tag         4
#define micro_mcp_ListResourcesResponse_resources_tag 1
#define micro_mcp_ReadResourceRequest_uri_tag    1
#define micro_mcp_ReadResourceResponse_contents_text_tag 1
#define micro_mcp_McpMessage_id_tag              1
#define micro_mcp_McpMessage_init_req_tag        2
#define micro_mcp_McpMessage_init_res_tag        3
#define micro_mcp_McpMessage_list_tools_req_tag  4
#define micro_mcp_McpMessage_list_tools_res_tag  5
#define micro_mcp_McpMessage_call_tool_req_tag   6
#define micro_mcp_McpMessage_call_tool_res_tag   7
#define micro_mcp_McpMessage_list_resources_req_tag 8
#define micro_mcp_McpMessage_list_resources_res_tag 9
#define micro_mcp_McpMessage_read_resource_req_tag 10
#define micro_mcp_McpMessage_read_resource_res_tag 11
#define micro_mcp_McpMessage_error_message_tag   15

/* Struct field encoding specification for nanopb */
#define micro_mcp_InitializeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   client_name,       2) \
X(a, STATIC,   SINGULAR, STRING,   client_version,    3)
#define micro_mcp_InitializeRequest_CALLBACK NULL
#define micro_mcp_InitializeRequest_DEFAULT NULL

#define micro_mcp_InitializeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   server_name,       2) \
X(a, STATIC,   SINGULAR, STRING,   server_version,    3)
#define micro_mcp_InitializeResponse_CALLBACK NULL
#define micro_mcp_InitializeResponse_DEFAULT NULL

#define micro_mcp_Tool_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   description,       2) \
X(a, STATIC,   SINGULAR, STRING,   input_schema_json,   3)
#define micro_mcp_Tool_CALLBACK NULL
#define micro_mcp_Tool_DEFAULT NULL

#define micro_mcp_ListToolsResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  tools,             1)
#define micro_mcp_ListToolsResponse_CALLBACK NULL
#define micro_mcp_ListToolsResponse_DEFAULT NULL
#define micro_mcp_ListToolsResponse_tools_MSGTYPE micro_mcp_Tool

#define micro_mcp_CallToolRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   arguments_json,    2)
#define micro_mcp_CallToolRequest_CALLBACK NULL
#define micro_mcp_CallToolRequest_DEFAULT NULL

#define micro_mcp_CallToolResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   content_text,      1) \
X(a, STATIC,   SINGULAR, BOOL,     is_error,          2)
#define micro_mcp_CallToolResponse_CALLBACK NULL
#define micro_mcp_CallToolResponse_DEFAULT NULL

#define micro_mcp_Resource_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uri,               1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, STRING,   description,       3) \
X(a, STATIC,   SINGULAR, STRING,   mime_type,         4)
#define micro_mcp_Resource_CALLBACK NULL
#define micro_mcp_Resource_DEFAULT NULL

#define micro_mcp_ListResourcesResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  resources,         1)
#define micro_mcp_ListResourcesResponse_CALLBACK NULL
#define micro_mcp_ListResourcesResponse_DEFAULT NULL
#define micro_mcp_ListResourcesResponse_resources_MSGTYPE micro_mcp_Resource

#define micro_mcp_ReadResourceRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uri,               1)
#define micro_mcp_ReadResourceRequest_CALLBACK NULL
#define micro_mcp_ReadResourceRequest_DEFAULT NULL

#define micro_mcp_ReadResourceResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   contents_text,     1)
#define micro_mcp_ReadResourceResponse_CALLBACK NULL
#define micro_mcp_ReadResourceResponse_DEFAULT NULL

#define micro_mcp_McpMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,init_req,message_type.init_req),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,init_res,message_type.init_res),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (message_type,list_tools_req,message_type.list_tools_req),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,list_tools_res,message_type.list_tools_res),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,call_tool_req,message_type.call_tool_req),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,call_tool_res,message_type.call_tool_res),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (message_type,list_resources_req,message_type.list_resources_req),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,list_resources_res,message_type.list_resources_res),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,read_resource_req,message_type.read_resource_req),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,read_resource_res,message_type.read_resource_res),  11) \
X(a, STATIC,   ONEOF,    STRING,   (message_type,error_message,message_type.error_message),  15)
#define micro_mcp_McpMessage_CALLBACK NULL
#define micro_mcp_McpMessage_DEFAULT NULL
#define micro_mcp_McpMessage_message_type_init_req_MSGTYPE micro_mcp_InitializeRequest
#define micro_mcp_McpMessage_message_type_init_res_MSGTYPE micro_mcp_InitializeResponse
#define micro_mcp_McpMessage_message_type_list_tools_res_MSGTYPE micro_mcp_ListToolsResponse
#define micro_mcp_McpMessage_message_type_call_tool_req_MSGTYPE micro_mcp_CallToolRequest
#define micro_mcp_McpMessage_message_type_call_tool_res_MSGTYPE micro_mcp_CallToolResponse
#define micro_mcp_McpMessage_message_type_list_resources_res_MSGTYPE micro_mcp_ListResourcesResponse
#define micro_mcp_McpMessage_message_type_read_resource_req_MSGTYPE micro_mcp_ReadResourceRequest
#define micro_mcp_McpMessage_message_type_read_resource_res_MSGTYPE micro_mcp_ReadResourceResponse

extern const pb_msgdesc_t micro_mcp_InitializeRequest_msg;
extern const pb_msgdesc_t micro_mcp_InitializeResponse_msg;
extern const pb_msgdesc_t micro_mcp_Tool_msg;
extern const pb_msgdesc_t micro_mcp_ListToolsResponse_msg;
extern const pb_msgdesc_t micro_mcp_CallToolRequest_msg;
extern const pb_msgdesc_t micro_mcp_CallToolResponse_msg;
extern const pb_msgdesc_t micro_mcp_Resource_msg;
extern const pb_msgdesc_t micro_mcp_ListResourcesResponse_msg;
extern const pb_msgdesc_t micro_mcp_ReadResourceRequest_msg;
extern const pb_msgdesc_t micro_mcp_ReadResourceResponse_msg;
extern const pb_msgdesc_t micro_mcp_McpMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define micro_mcp_InitializeRequest_fields &micro_mcp_InitializeRequest_msg
#define micro_mcp_InitializeResponse_fields &micro_mcp_InitializeResponse_msg
#define micro_mcp_Tool_fields &micro_mcp_Tool_msg
#define micro_mcp_ListToolsResponse_fields &micro_mcp_ListToolsResponse_msg
#define micro_mcp_CallToolRequest_fields &micro_mcp_CallToolRequest_msg
#define micro_mcp_CallToolResponse_fields &micro_mcp_CallToolResponse_msg
#define micro_mcp_Resource_fields &micro_mcp_Resource_msg
#define micro_mcp_ListResourcesResponse_fields &micro_mcp_ListResourcesResponse_msg
#define micro_mcp_ReadResourceRequest_fields &micro_mcp_ReadResourceRequest_msg
#define micro_mcp_ReadResourceResponse_fields &micro_mcp_ReadResourceResponse_msg
#define micro_mcp_McpMessage_fields &micro_mcp_McpMessage_msg

/* Maximum encoded size of messages (where known) */
#define MICRO_MCP_MCP_PB_H_MAX_SIZE              micro_mcp_McpMessage_size
#define micro_mcp_CallToolRequest_size           291
#define micro_mcp_CallToolResponse_size          260
#define micro_mcp_InitializeRequest_size         67
#define micro_mcp_InitializeResponse_size        67
#define micro_mcp_ListResourcesResponse_size     1990
#define micro_mcp_ListToolsResponse_size         2310
#define micro_mcp_McpMessage_size                2324
#define micro_mcp_ReadResourceRequest_size       65
#define micro_mcp_ReadResourceResponse_size      514
#define micro_mcp_Resource_size                  196
#define micro_mcp_Tool_size                      228

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
