/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "micro_mcp/mcp.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(micro_mcp_InitializeRequest, micro_mcp_InitializeRequest, AUTO)


PB_BIND(micro_mcp_InitializeResponse, micro_mcp_InitializeResponse, AUTO)


PB_BIND(micro_mcp_Tool, micro_mcp_Tool, AUTO)


PB_BIND(micro_mcp_ListToolsResponse, micro_mcp_ListToolsResponse, 2)


PB_BIND(micro_mcp_CallToolRequest, micro_mcp_CallToolRequest, 2)


PB_BIND(micro_mcp_CallToolResponse, micro_mcp_CallToolResponse, 2)


PB_BIND(micro_mcp_Resource, micro_mcp_Resource, AUTO)


PB_BIND(micro_mcp_ListResourcesResponse, micro_mcp_ListResourcesResponse, 2)


PB_BIND(micro_mcp_ReadResourceRequest, micro_mcp_ReadResourceRequest, AUTO)


PB_BIND(micro_mcp_ReadResourceResponse, micro_mcp_ReadResourceResponse, 2)


PB_BIND(micro_mcp_McpMessage, micro_mcp_McpMessage, 2)



